import google.generativeai as genai  # Importing the Google Gemini AI module

# Function to load Gemini model and get response for image
def get_gemini_response(image):
    """
    This function takes an image as input, loads the Gemini model ('gemini-pro-vision'),
    and generates a response based on the image content using the Gemini model.
    It returns the text response generated by the model.
    """
    model = genai.GenerativeModel('gemini-pro-vision')  # Load Gemini model
    if image:  # Check if image is provided
        response = model.generate_content([image])  # Generate response for image
    else:
        response = model.generate_content(image)  # Generate response for empty image
    return response.text  # Return the text response generated by the model