import google.generativeai as genai  # Importing the Google Gemini AI module

# Function to load Gemini model and get response for text
def get_gemini_response_text(given_text):
    """
    This function takes a text input, loads the Gemini model ('gemini-pro'),
    and generates a response based on the input text using the Gemini model.
    It returns the text response generated by the model.
    """
    model = genai.GenerativeModel('gemini-pro')  # Load Gemini model
    response = model.generate_content(given_text)  # Generate response for text
    return response.text  # Return the text response generated by the model